name: License Compliance CI
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Check licenses
        run: npx license-checker --production --failOn "GPL;AGPL"
